# Server
server:
  port: 8086
spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/notificationdb
    username: postgres
    password: MYPOSTGRESQL

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Mail (Gmail)
  mail:
    host: smtp.gmail.com
    port: 587
    username: monsef.rh15@gmail.com
    password: "*"
    properties:
      mail:
        smtp:
          from: "E-banking App Team <monsef.rh15@gmail.com>"
          auth: true
          starttls:
            enable: true
